### PR TITLE
Added windows/input support, small refactors

### PR DESCRIPTION
**Pull request by lolp1**
Since I enjoyed the project, I spent a bit adding my window/input classes to the project to possibly as I noticed you started to add your own input stuff.

Feel free to give the classes a test/make suggestions.

It can be used like so:
```chsarp
            var process = Process.GetProcessesByName("notepad").FirstOrDefault();
            var window = new RemoteWindow(process.MainWindowHandle);
            window.Keyboard.PressRelease(Keys.Down);
```

API provided/default implementations provided from the classes:

    public interface IWindow : IDisposable
    {
        IEnumerable<IWindow> Children { get; }
        string ClassName { get; }
        IntPtr Handle { get; }
        int Height { get; set; }
        bool IsActivated { get; }
        IKeyboard Keyboard { get; set; }
        IMouse Mouse { get; set; }
        WindowPlacement Placement { get; set; }
        WindowStates State { get; set; }
        string Title { get; set; }
        int Width { get; set; }
        int X { get; set; }
        int Y { get; set; }
        void Activate();
        void Close();
        void Flash();
        void Flash(int count, TimeSpan timeout, FlashWindowFlags flags = FlashWindowFlags.All);
        void PostMessage(WM message, IntPtr wParam, IntPtr lParam);
        void PostMessage(int message, IntPtr wParam, IntPtr lParam);
        IntPtr SendMessage(WM message, IntPtr wParam, IntPtr lParam);
        IntPtr SendMessage(int message, IntPtr wParam, IntPtr lParam);
    }

    public interface IKeyboard
    {
        void Press(Keys key, TimeSpan interval);
        void PressRelease(Keys key);
        void Write(string text, params object[] args);
        void Press(Keys key);
        void Write(char character);
    }

    public interface IMouse
    {
        void ClickLeft();
        void ClickMiddle();
        void ClickRight();
        void DoubleClickLeft();
        void MoveTo(int x, int y);
        void PressLeft();
        void PressMiddle();
        void PressRight();
        void ReleaseLeft();
        void ReleaseMiddle();
        void ReleaseRight();
        void ScrollHorizontally(int delta = 120);
        void ScrollVertically(int delta = 120);
    }

### CODE REVIEW

**Comment by lolp1** [comment]
@Zakamurite @Dramacydal 

Any plans to merge these changes :)? I see it has been a while since you touched the project.

**Comment by lolp1** [comment]
@Dramacydal Was hoping to be of use but seems you did your own thing on this front, closing request. Cool project none the less. Keep on the x64 support path Imo!

**Comment by Dramacydal** [comment]
@lolp1 LOL how could I miss this PR :fearful: 
It is very interesting, so do your interop projects
I will definitely look into it, but it seems to be a bit outdated for now
First of all this project was intended to be used only for memory operations/debugging
Then i started to add other win32/interop stuff to it, but it actually disturbs me
Now it looks as a complete code garbage. Well, it was since beginning with my code skills.
I will check your modifications as soon as I can

**Comment by Dramacydal** [comment]
I was thinking about adding x64 support long ago, but I can't find a solution to support both x32/x64 in signle library with all those structure differences. Also it would require major refactoring

**Comment by lolp1** [comment]
> 
> 
> I was thinking about adding x64 support long ago, but I can't find a solution to support both x32/x64 in signle library with all those structure differences. Also it would require major refactoring

@Dramacydal The vast majority of things are just using an IntPtr fields for architecture stuff. You are right, this pull request would be too difficult to fit in at this stage/would not make much sense. 

The main thing that I noticed right away about your project was the hardware breakpoints usage. I had done some VEH stuff and writing to memory somewhere to throw exceptions at a call I wanted to intercept, but I've never seen true hardware breakpoints in a C# project!

**Pull request closed without merging**
